language: java
jdk:
    - openjdk8
before_install:
    - chmod +x gradlew
    - ". $HOME/.nvm/nvm.sh"
    - nvm install stable
    - nvm use stable
    - cd .utility && npm install && cd ..
install: "./gradlew setupCIWorkspace -S"
script:
    - "./gradlew build -S"
    - "./gradlew userdocs -q"
after_success:
    - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
    - cd .utility/
    - npm run deploy-docs
    #- npm run deploy-jars
after_failure:
    - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL