modLoader="javafml"
loaderVersion="[33,)"
license="MIT"
issueTrackerURL="https://github.com/ChatTriggers/ChatTriggers/issues"

[[mods]]
modId="chattriggers"
version="${global.mcVersion}"
displayName="ChatTriggers"
displayURL="https://chattriggers.com"
description="A mod which lets users easily create simple game modifications using JavaScript"
logoFile="images/CT_logo.png"
authors="FalseHonesty, Ecolsson, kerbybit"

[[dependencies.chattriggers]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"

[[dependencies.chattriggers]]
modId="minecraft"
mandatory=true
versionRange="[${global.mcVersion}]"
ordering="NONE"
side="BOTH"